insert into drink (id, nama_minuman, harga) values (1, 'Bread - Crumbs, Bulk', '6135.06');
insert into drink (id, nama_minuman, harga) values (2, 'Turnip - Mini', '3108.35');
insert into drink (id, nama_minuman, harga) values (3, 'Russian Prince', '2770.75');
insert into drink (id, nama_minuman, harga) values (4, 'Cheese - Wine', '1082.96');
insert into drink (id, nama_minuman, harga) values (5, 'Cheese - Cheddar, Old White', '8819.33');
insert into drink (id, nama_minuman, harga) values (6, 'Snapple - Mango Maddness', '2404.81');
insert into drink (id, nama_minuman, harga) values (7, 'Pastry - Chocolate Marble Tea', '3318.92');
insert into drink (id, nama_minuman, harga) values (8, 'Beer - Heinekin', '4270.07');
insert into drink (id, nama_minuman, harga) values (9, 'Energy Drink', '3915.25');
insert into drink (id, nama_minuman, harga) values (10, 'Sesame Seed Black', '8959.31');
insert into drink (id, nama_minuman, harga) values (11, 'Asparagus - White, Fresh', '4808.84');
insert into drink (id, nama_minuman, harga) values (12, 'Orange - Blood', '9450.67');
insert into drink (id, nama_minuman, harga) values (13, 'Beer - Original Organic Lager', '1371.61');
insert into drink (id, nama_minuman, harga) values (14, 'Spring Roll Wrappers', '382.31');
insert into drink (id, nama_minuman, harga) values (15, 'Veal - Sweetbread', '1945.29');
insert into drink (id, nama_minuman, harga) values (16, 'Gelatine Powder', '8887.24');
insert into drink (id, nama_minuman, harga) values (17, 'Ocean Spray - Ruby Red', '4530.87');
insert into drink (id, nama_minuman, harga) values (18, 'Vinegar - Cider', '1905.96');
insert into drink (id, nama_minuman, harga) values (19, 'Spring Roll Wrappers', '6371.68');
insert into drink (id, nama_minuman, harga) values (20, 'Soup - Cream Of Broccoli', '4911.04');
insert into drink (id, nama_minuman, harga) values (21, 'Baking Powder', '6553.45');
insert into drink (id, nama_minuman, harga) values (22, 'Carrots - Mini, Stem On', '5570.97');
insert into drink (id, nama_minuman, harga) values (23, 'Juice - Cranberry 284ml', '6681.28');
insert into drink (id, nama_minuman, harga) values (24, 'Juice - Apple, 341 Ml', '8145.63');
insert into drink (id, nama_minuman, harga) values (25, 'Cranberries - Frozen', '5900.73');
insert into drink (id, nama_minuman, harga) values (26, 'Bacon Strip Precooked', '827.97');
insert into drink (id, nama_minuman, harga) values (27, 'Pan Grease', '9615.32');
insert into drink (id, nama_minuman, harga) values (28, 'Sauce - Mint', '3798.10');
insert into drink (id, nama_minuman, harga) values (29, 'Onions - White', '693.32');
insert into drink (id, nama_minuman, harga) values (30, 'Coffee - Decaffeinato Coffee', '2475.66');
insert into drink (id, nama_minuman, harga) values (31, 'Nut - Hazelnut, Whole', '8710.12');
insert into drink (id, nama_minuman, harga) values (32, 'Miso Paste White', '9941.49');
insert into drink (id, nama_minuman, harga) values (33, 'Sugar - Brown, Individual', '1269.36');
insert into drink (id, nama_minuman, harga) values (34, 'Trout - Rainbow, Fresh', '8399.78');
insert into drink (id, nama_minuman, harga) values (35, 'Pancetta', '398.37');
insert into drink (id, nama_minuman, harga) values (36, 'Bacardi Limon', '8573.90');
insert into drink (id, nama_minuman, harga) values (37, 'Magnotta Bel Paese Red', '7700.43');
insert into drink (id, nama_minuman, harga) values (38, 'Wine - Red, Harrow Estates, Cab', '6022.54');
insert into drink (id, nama_minuman, harga) values (39, 'Pepper - Chili Powder', '9886.81');
insert into drink (id, nama_minuman, harga) values (40, 'Mountain Dew', '6524.84');
insert into drink (id, nama_minuman, harga) values (41, 'Pancetta', '3687.29');
insert into drink (id, nama_minuman, harga) values (42, 'Extract Vanilla Pure', '8094.73');
insert into drink (id, nama_minuman, harga) values (43, 'Cut Wakame - Hanawakaba', '5466.39');
insert into drink (id, nama_minuman, harga) values (44, 'White Baguette', '2624.28');
insert into drink (id, nama_minuman, harga) values (45, 'Brandy - Orange, Mc Guiness', '285.66');
insert into drink (id, nama_minuman, harga) values (46, 'Pepper - Jalapeno', '5693.69');
insert into drink (id, nama_minuman, harga) values (47, 'Vinegar - White Wine', '4087.90');
insert into drink (id, nama_minuman, harga) values (48, 'Wine - Ej Gallo Sierra Valley', '296.59');
insert into drink (id, nama_minuman, harga) values (49, 'Boogies', '7191.71');
insert into drink (id, nama_minuman, harga) values (50, 'Wine - Trimbach Pinot Blanc', '4938.63');
insert into drink (id, nama_minuman, harga) values (51, 'Ocean Spray - Ruby Red', '4243.77');
insert into drink (id, nama_minuman, harga) values (52, 'Straw - Regular', '3551.32');
insert into drink (id, nama_minuman, harga) values (53, 'Dried Apple', '2041.20');
insert into drink (id, nama_minuman, harga) values (54, 'Wine - Bouchard La Vignee Pinot', '7143.66');
insert into drink (id, nama_minuman, harga) values (55, 'Trout - Hot Smkd, Dbl Fillet', '7024.44');
insert into drink (id, nama_minuman, harga) values (56, 'Coconut - Creamed, Pure', '3237.94');
insert into drink (id, nama_minuman, harga) values (57, 'Sambuca - Ramazzotti', '7917.64');
insert into drink (id, nama_minuman, harga) values (58, 'Wine - Malbec Trapiche Reserve', '2705.54');
insert into drink (id, nama_minuman, harga) values (59, 'Bread - Sticks, Thin, Plain', '1806.47');
insert into drink (id, nama_minuman, harga) values (60, 'Grapes - Black', '5014.11');
insert into drink (id, nama_minuman, harga) values (61, 'Beer - Upper Canada Light', '2366.74');
insert into drink (id, nama_minuman, harga) values (62, 'Vinegar - Tarragon', '256.28');
insert into drink (id, nama_minuman, harga) values (63, 'French Pastries', '7974.20');
insert into drink (id, nama_minuman, harga) values (64, 'Cake Circle, Paprus', '2201.65');
insert into drink (id, nama_minuman, harga) values (65, 'Assorted Desserts', '4777.32');
insert into drink (id, nama_minuman, harga) values (66, 'Wine - Fat Bastard Merlot', '6657.25');
insert into drink (id, nama_minuman, harga) values (67, 'Beets - Mini Golden', '5594.87');
insert into drink (id, nama_minuman, harga) values (68, 'Chinese Foods - Plain Fried Rice', '4916.95');
insert into drink (id, nama_minuman, harga) values (69, 'Sugar - Crumb', '3607.34');
insert into drink (id, nama_minuman, harga) values (70, 'Cheese - Wine', '1198.50');
insert into drink (id, nama_minuman, harga) values (71, 'Veal - Brisket, Provimi, Bone - In', '382.41');
insert into drink (id, nama_minuman, harga) values (72, 'Gingerale - Schweppes, 355 Ml', '4744.64');
insert into drink (id, nama_minuman, harga) values (73, 'Table Cloth 62x120 White', '5114.81');
insert into drink (id, nama_minuman, harga) values (74, 'Beef Striploin Aaa', '7317.55');
insert into drink (id, nama_minuman, harga) values (75, 'Cheese - Cheddar, Mild', '9803.57');
insert into drink (id, nama_minuman, harga) values (76, 'Oil - Olive', '122.88');
insert into drink (id, nama_minuman, harga) values (77, 'Pasta - Lasagne, Fresh', '6920.95');
insert into drink (id, nama_minuman, harga) values (78, 'Pastry - Choclate Baked', '8406.36');
insert into drink (id, nama_minuman, harga) values (79, 'Pastry - Butterscotch Baked', '9962.22');
insert into drink (id, nama_minuman, harga) values (80, 'Oranges', '7363.79');
insert into drink (id, nama_minuman, harga) values (81, 'Water - Spring 1.5lit', '7518.52');
insert into drink (id, nama_minuman, harga) values (82, 'Chicken - Diced, Cooked', '1224.97');
insert into drink (id, nama_minuman, harga) values (83, 'Jam - Strawberry, 20 Ml Jar', '6497.26');
insert into drink (id, nama_minuman, harga) values (84, 'Pears - Bartlett', '2303.80');
insert into drink (id, nama_minuman, harga) values (85, 'Calypso - Pineapple Passion', '9783.95');
insert into drink (id, nama_minuman, harga) values (86, 'Pants Custom Dry Clean', '1776.98');
insert into drink (id, nama_minuman, harga) values (87, 'Tea - Darjeeling, Azzura', '6449.38');
insert into drink (id, nama_minuman, harga) values (88, 'Wine - Zinfandel Rosenblum', '6506.37');
insert into drink (id, nama_minuman, harga) values (89, 'Creme De Cacao White', '4791.01');
insert into drink (id, nama_minuman, harga) values (90, 'Halibut - Fletches', '2560.91');
insert into drink (id, nama_minuman, harga) values (91, 'Bulgar', '8977.48');
insert into drink (id, nama_minuman, harga) values (92, 'Beef - Chuck, Boneless', '3255.34');
insert into drink (id, nama_minuman, harga) values (93, 'Whmis Spray Bottle Graduated', '6511.24');
insert into drink (id, nama_minuman, harga) values (94, 'Jicama', '9565.84');
insert into drink (id, nama_minuman, harga) values (95, 'Beef - Tongue, Fresh', '3360.77');
insert into drink (id, nama_minuman, harga) values (96, 'Clam Nectar', '3547.30');
insert into drink (id, nama_minuman, harga) values (97, 'Beef - Striploin Aa', '1890.87');
insert into drink (id, nama_minuman, harga) values (98, 'Sauce - Alfredo', '9196.84');
insert into drink (id, nama_minuman, harga) values (99, 'Pastry - Cheese Baked Scones', '7523.81');
insert into drink (id, nama_minuman, harga) values (100, 'Chocolate - Milk, Callets', '6263.18');